# This is the cross compile definition for the meson "Unix 64 bit" target.

[binaries]
#c   = 'clang'
#cpp = 'clang++'
c   = 'gcc'
cpp = 'g++'
#pkg-config = '/usr/bin/arm-linux-gnueabihf-pkg-config'
#pkg-config = '${HOME}/tmp/pkg-config'
c_ld = 'lld'
cpp_ld = 'lld'
