dumpgdl90         = executable('dumpGDL90', 'DumpGDL90.cpp')
cutgdl90before    = executable('cutGDL90before', [ 'CutGDL90Before.cpp',
                                                   'Utilities.cpp' ],
                               cpp_args : '-Wno-missing-declarations',
                              )
cutgdl90after     = executable('cutGDL90after' , [ 'CutGDL90After.cpp',
                                                   'Utilities.cpp' ],
                               cpp_args : '-Wno-missing-declarations',
                              )
