#!/bin/bash

[ -d subprojects/airspace_sources ] || mkdir subprojects/airspace_sources
echo "project('Airspace_Sources')" > subprojects/airspace_sources/meson.build
echo "airspace_sources = [" >> subprojects/airspace_sources/meson.build
echo -n "'" >> subprojects/airspace_sources/meson.build
grep "^AIRSPACE_SOURCES" | \
sed -e 's/AIRSPACE_SOURCES = //' | \
sed -e 's:\$(AIRSPACE_SRC_DIR)/::g' | \
sed -e 's:\$(ENGINE_SRC_DIR):..:' | \
sed -e "s/ /',\n'/g" | \
sed -e "s/cpp$/cpp'/" >> subprojects/airspace_sources/meson.build
echo " ]" >> subprojects/airspace_sources/meson.build
