#!/bin/bash

[ -d subprojects/cloudtokml_sources ] || mkdir subprojects/cloudtokml_sources
echo "project('Cloudtokml_Sources')" > subprojects/cloudtokml_sources/meson.build
echo "cloudtokml_sources = [" >> subprojects/cloudtokml_sources/meson.build
echo -n "'" >> subprojects/cloudtokml_sources/meson.build
grep "^CLOUD_TO_KML_SOURCES = " | \
sed -e 's/CLOUD_TO_KML_SOURCES = //' | \
sed -e 's:\$(SRC)/Cloud/::g' | \
sed -e 's:\$(SRC)/Tracking/SkyLines/:../Tracking/SkyLines/:g' | \
sed -e "s/ /',\n'/g" | \
sed -e "s/'$//" |
sed -e "s:cpp$:cpp':g" >> subprojects/cloudtokml_sources/meson.build
echo " ]" >> subprojects/cloudtokml_sources/meson.build
