#!/bin/bash

[ -d subprojects/event_sources ] || mkdir subprojects/event_sources
echo "project('Event_Sources')" > subprojects/event_sources/meson.build
echo "event_sources = [" >> subprojects/event_sources/meson.build
echo -n "'" >> subprojects/event_sources/meson.build
grep "^EVENT_SOURCES = " | \
sed -e 's/EVENT_SOURCES = //' | \
sed -e 's:\$(SRC)/ui/event/::g' | \
sed -e "s/ /',\n'/g" | \
sed -e "s/'$//" |
sed -e "s:cpp$:cpp':g" >> subprojects/event_sources/meson.build
echo " ]" >> subprojects/event_sources/meson.build
