#!/bin/bash

[ -d subprojects/infobox_sources ] || mkdir subprojects/infobox_sources
echo "project('Infobox_Sources')" > subprojects/infobox_sources/meson.build
echo "infobox_sources = [" >> subprojects/infobox_sources/meson.build
echo -n "'" >> subprojects/infobox_sources/meson.build
grep "^LIBINFOBOX_SOURCES" | \
sed -e 's/LIBINFOBOX_SOURCES = //' | \
sed -e 's:\$(SRC)/InfoBoxes/::g' | \
sed -e "s/ /',\n'/g" | \
sed -e "s/cpp$/cpp'/" >> subprojects/infobox_sources/meson.build
echo " ]" >> subprojects/infobox_sources/meson.build
