#!/bin/bash

[ -d subprojects/lua_sources ] || mkdir subprojects/lua_sources
echo "project('Lua_Sources')" > subprojects/lua_sources/meson.build
echo "lua_sources = [" >> subprojects/lua_sources/meson.build
echo -n "'" >> subprojects/lua_sources/meson.build
grep "^LUA_SOURCES = " | \
sed -e 's/LUA_SOURCES = //' | \
sed -e 's:\$(SRC)/lua/::g' | \
sed -e "s/ /',\n'/g" | \
sed -e "s/'$//" |
sed -e "s:cpp$:cpp':g" >> subprojects/lua_sources/meson.build
echo " ]" >> subprojects/lua_sources/meson.build
