#!/bin/bash

[ -d subprojects/net_sources ] || mkdir subprojects/net_sources
echo "project('Net_Sources')" > subprojects/net_sources/meson.build
echo "net_sources = [" >> subprojects/net_sources/meson.build
echo -n "'" >> subprojects/net_sources/meson.build
grep "^LIBNET_SOURCES" | \
sed -e 's/LIBNET_SOURCES = //' | \
sed -e 's:\$(SRC)/net/::g' | \
sed -e "s/ /',\n'/g" | \
sed -e "s/cxx$/cxx'/" >> subprojects/net_sources/meson.build
echo " ]" >> subprojects/net_sources/meson.build
