#!/bin/bash

[ -d subprojects/profile_sources ] || mkdir subprojects/profile_sources
echo "project('Profile_Sources')" > subprojects/profile_sources/meson.build
echo "profile_sources = [" >> subprojects/profile_sources/meson.build
echo -n "'" >> subprojects/profile_sources/meson.build
grep "^PROFILE_SOURCES" | \
sed -e 's/PROFILE_SOURCES = //' | \
sed -e 's:\$(SRC)/Profile/::g' | \
sed -e "s/ /',\n'/g" | \
sed -e "s/cpp$/cpp'/" >> subprojects/profile_sources/meson.build
echo " ]" >> subprojects/profile_sources/meson.build
