#!/bin/bash

[ -d subprojects/terrain_sources ] || mkdir subprojects/terrain_sources
echo "project('Terrain_Sources')" > subprojects/terrain_sources/meson.build
echo "terrain_sources = [" >> subprojects/terrain_sources/meson.build
echo -n "'" >> subprojects/terrain_sources/meson.build
grep "^TERRAIN_SOURCES" | \
sed -e 's/TERRAIN_SOURCES = //' | \
sed -e 's:\$(SRC)/Terrain/::g' | \
sed -e "s/ /',\n'/g" | \
sed -e "s/cpp$/cpp'/" >> subprojects/terrain_sources/meson.build
echo " ]" >> subprojects/terrain_sources/meson.build
