#!/bin/bash

[ -d subprojects/widget_sources ] || mkdir subprojects/widget_sources
echo "project('Widget_Sources')" > subprojects/widget_sources/meson.build
echo "widget_sources = [" >> subprojects/widget_sources/meson.build
echo -n "'" >> subprojects/widget_sources/meson.build
grep "^WIDGET_SOURCES" | \
sed -e 's/WIDGET_SOURCES = //' | \
sed -e 's:\$(SRC)/Widget/::g' | \
sed -e "s/ /',\n'/g" | \
sed -e "s/cpp$/cpp'/" >> subprojects/widget_sources/meson.build
echo " ]" >> subprojects/widget_sources/meson.build
