cpnmea         = executable('cpnmea', 'cpNMEA.cpp',
                            cpp_args : '-Wno-missing-declarations',
                           )
mkspectrumplot = executable('mkspectrumplot', 'MkSpectrumPlot.cpp')
mkscan         = executable('mkscan', 'MkScan.cpp',
                            cpp_args : '-Wno-missing-declarations',
                           )
