#!/bin/bash

# This generates the old resources header to stdout from stdin.
#
# Moved from CMakeLists.txt to here in order to avoid any crazy syntax
# problems with cmake.

grep "^MAKE_RESOURCE" | sed -e 's:MAKE_RESOURCE(:#define :' | sed -e 's:,: :' | sed -e 's:);::'
