project('Cloudtokml_Sources')
cloudtokml_sources = [
'../Tracking/SkyLines/Assemble.cpp',
'Serialiser.cpp',
'Data.cpp',
'ToKML.cpp'
 ]
# The following is necessary because these routines use some Boost library
#  which triggers "error: unused parameter"
cloudtokml_unused_parameter_sources = [
'Client.cpp',
'Thermal.cpp',
 ]
